### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by risih** [cyckl/cheerleadingisntasport.org#5]
The author of this repository is currently deceased. As a result, projects associated with the author are no longer actively maintained. If you are currently dependent on any of his software, please consider making a fork to keep development going, or finding alternative software. 

As a close friend of the author, I am deeply touched and saddened by Daniel's untimely passing. Although I am not in a position to reveal the details of his passing, his tragic loss could have been prevented if not for an unfortunate combination of a ceiling fan, 5 meters of rope, the male reproductive organ, and his trademark hedonistic worldview. I feel obliged to help support Daniel's family in any way possible, and keep his memory alive. Donations would be greatly appreciated, and if you have the money to spare, it could make a difference.

**Comment by doamatto** [comment]
As a true friend of Daniel, I'm even more heartbroken than risih here. I'll be closing this issue using mind powers to keep this from being blown out of proportion. Until then, you can donate directly to me to help pay for the burial costs. You can also write your condolences direct to me.

**Comment by risih** [comment]
As an even closer friend of Daniel, I am the most heartbroken person here, and find @doamatto's claim suggesting otherwise to be wholly unsubstantiated and abhorrent. Please wire me 100,000 USD as it will most definitely serve a good cause.

**Comment by doamatto** [comment]
Please stop necroposting on this heartbreaking story. This kind of abuse is not tolerated in this community, nor on GitHub.

**Comment by cyckl** [comment]
I have risen.

**Comment by cyckl** [comment]
Best,
@doamatto
